server:
  port: 8890
logging:
  config: classpath:logback-spring.xml
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /test
    host: 10.162.16.24
    queue:
      listeners:
        testListener:
          queueNames: test
          minConsumer: 1
          maxConsumer: 1
          threadMaxSize: 1
      enableListener: true

