spring:
  config:
    import: 'optional:consul:'
  application:
    name: escanor-job
  profiles:
    active: docker
  cloud:
    gateway:
      metrics:
        enabled: true
    consul:
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        health-check-interval: '30s'
        health-check-tls-skip-verify: true
        tags: user.name=consul, user.password=consul
        #scheme: https
      config:
        data-key: configuration
        enabled: true
        watch:
          enabled: true
        profile-separator: '::'
        format: yaml
        fail-fast: false
      host: 192.168.50.126

---
spring:
  cloud:
    consul:
      host: host.docker.internal
      discovery:
        ip-address: 127.0.0.1
  config:
    activate:
      on-profile: docker