server:
  port: 8888

spring:
  enableMultiDs: true
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /test
    host: 10.162.16.24
    bindings:
      auto:
        defaultKey: auto
        defaultQueue: auto
        mappers:
          - code: 6447
            queue: auto6447
    queue:
      listeners:
        testListener:
          queueNames: auto
          minConsumer: 1
          maxConsumer: 1
          threadMaxSize: 1
        test6447Listener:
          queueNames: auto6447
          minConsumer: 1
          maxConsumer: 1
          threadMaxSize: 1
      enableListener: true
    template:
      exchange: auto
      routing-key: auto
  datasources:
    default:
      name: default
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: wmliu
      password: 876286443
      driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 120000
      supports: '6447'

    test:
      name: test
      url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      username: wmliu
      password: 876286443
      driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 120000
      supports: '6438'
  sleuth:
    default-logging-pattern-enabled: true