server:
  port: 8890
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/escanor?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8"
    username: escanor
    password: escanor
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /test
    host: 10.162.16.24
    bindings:
      auto:
        defaultKey: auto
        defaultQueue: auto
        mappers:
          - code: 6447
            queue: auto6447
    queue:
      listeners:
        testListener:
          queueNames: auto
          minConsumer: 1
          maxConsumer: 1
        test6447Listener:
          queueNames: auto6447
          minConsumer: 1
          maxConsumer: 1
      enableListener: true
    template:
      exchange: auto
      routing-key: auto