server:
  port: 8887
spring:
  security:
    oauth2:
      client:
        registration:
          auth0525:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          auth0525:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
        connect-timeout: 10000
        response-timeout: 120s
      routes:
        - id: escanor-multids
          uri: lb://escanor-multids
          predicates:
            - Path=/multids/**
          filters:
            - StripPrefix=1
    loadbalancer:
      ribbon:
        enabled: false

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always