server:
  port: 8889
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
shiro:
  enabled: true
feign:
  client:
    config:
      escanor-user-service:
        connectTimeout: 5000
        readTimeout: 5000
        defaultRequestHeaders:
          IgnoreWrapResponse: "true"